Feature/list invitations
GameFuse-PA/mobile pull request #11
Opened 2023-07-17 18:20 UTC by ShadowZ11

Listing des invitations sans la possibilité d'accepter ou de refuser

2023-07-18 10:33 UTC, noeoxycode requested changes

2023-07-18 10:33 UTC, noeoxycode commented on app/src/main/java/com/gamefuse/app/listInvitations/MyInvitationsFragment.kt
> +        val textNoInvitations: TextView = view.findViewById(R.id.empty_list_text)
tu devrais initialiser les éléments hors méthodes, et les setter dans onCreatedView, ça t'évitera de devoir le passer en paramètre de getInvitation pour textNoInvisations par exemple

2023-07-18 10:33 UTC, noeoxycode commented on app/src/main/java/com/gamefuse/app/listInvitations/MyInvitationsFragment.kt
> +        getInvitations(listInvitations, textNoInvitations, recyclerView)
l'endroit où tu transmet la textview comme cité au dessus : le mettre en attribut de classe te permettra d'éviter ça (textNoInvitations)

2023-07-18 10:33 UTC, noeoxycode commented on app/src/main/java/com/gamefuse/app/listInvitations/MyInvitationsFragment.kt
> +                    Toast.makeText(context, "Impossible de récupérer vos invitations", Toast.LENGTH_LONG).show()
on ne devrait pas mettre les textes des toats en variable string également ?

2023-07-18 10:33 UTC, noeoxycode commented on app/src/main/java/com/gamefuse/app/listInvitations/adapter/MyInvitationsAdapter.kt
> +        val executor = Executors.newSingleThreadExecutor()
pourquoi pas une coroutine ?

2023-07-18 10:33 UTC, noeoxycode commented on app/src/main/java/com/gamefuse/app/listInvitations/adapter/MyInvitationsAdapter.kt
> +            builder.setTitle("Ajout d'un ami")
à mettre en string

2023-07-18 10:33 UTC, noeoxycode commented on app/src/main/java/com/gamefuse/app/listInvitations/adapter/MyInvitationsAdapter.kt
> +            builder.setMessage("Voulez-vous vraiment accepter l'invitation de " + invitation.username + " ?")
idem

2023-07-18 10:33 UTC, noeoxycode commented on app/src/main/java/com/gamefuse/app/listInvitations/adapter/MyInvitationsAdapter.kt
> +            builder.setPositiveButton("Oui", DialogInterface.OnClickListener(function = positiveButton))
bref il y en a d'autres dans le fichier il faut les variabiliser

2023-07-18 10:33 UTC, noeoxycode commented on app/src/main/res/values/strings.xml
> +    <string name="no_invitations_text">You have no invitations yet</string>
plutot friendRequest

2023-07-18 10:33 UTC, noeoxycode commented on app/src/main/res/values-fr/strings.xml
> +    <string name="manage_invitation_image">Image accepter/refuser invit</string>
pourquoi ''Image'' je ne comprend pas

2023-07-18 13:18 UTC, ShadowZ11 commented on app/src/main/res/values-fr/strings.xml
> +    <string name="manage_invitation_image">Image accepter/refuser invit</string>
Alors ça c'est une bonne pratique pour les imageview dans le xml, c'est un peu l'équivalent du alt dans les balises img dans le cas où ça ne s'afficherait pas

2023-07-18 13:25 UTC, ShadowZ11 commented on app/src/main/java/com/gamefuse/app/listInvitations/adapter/MyInvitationsAdapter.kt
> +        val executor = Executors.newSingleThreadExecutor()
Ouais la j'avoue j'ai fait un thread parce que y'a pas de call api derrière donc en soit je pense que ça revient au même

2023-07-20 22:14 UTC, noeoxycode requested changes

2023-07-20 22:14 UTC, noeoxycode commented on app/src/main/res/values-fr/strings.xml
> +    <string name="my_invitations">Mes Invitations</string>
Mes demandes d'amis ou truc du genre en rapport avec l'amitié : invitaiton c'est trop vague

2023-07-21 21:42 UTC, ShadowZ11 commented on app/src/main/res/values-fr/strings.xml
> +    <string name="my_invitations">Mes Invitations</string>
Bah j'avoue que la j'ai juste recopier le design et en soit sachant que sur l'app y'a juste la partie sociale en soit mes invitations t'aura jamais autre chose que ajouter des amis

2023-07-22 10:38 UTC, noeoxycode approved these changes

2023-07-22 11:12 UTC, merged