Feature/profil page
GameFuse-PA/mobile pull request #12
Opened 2023-07-17 18:27 UTC by ShadowZ11

Ajout profil page sans la possibilité de sauvegarder mes changement d'informations pour le moment

2023-07-18 09:51 UTC, noeoxycode requested changes

2023-07-18 09:51 UTC, noeoxycode commented on app/src/main/java/com/gamefuse/app/profil/ProfilFragment.kt
> +
fonction vide

2023-07-18 12:56 UTC, ShadowZ11 commented on app/src/main/java/com/gamefuse/app/profil/ProfilFragment.kt
> +
Ouais ça c'était plus pour préparer la suite pour la pr de la sauvegarde du changement mais je le retire comme ça ça fait pas vide

2023-07-20 22:17 UTC, noeoxycode approved these changes

2023-07-21 20:25 UTC, merged