Feature/list friends
GameFuse-PA/mobile pull request #3
Opened 2023-06-22 21:28 UTC by ShadowZ11

2023-06-29 19:54 UTC, noeoxycode requested changes

2023-06-29 19:54 UTC, noeoxycode commented on app/src/main/java/com/gamefuse/app/API.kt
> +        .baseUrl("http://192.168.1.105:3000")
ça va falloir qu'on le gère car sinon on va se bagarrer sur chaque commit : un coup ce sera ton ip et un coup la mienne

2023-06-29 19:54 UTC, noeoxycode commented on app/src/main/java/com/gamefuse/app/myFriendsList/FriendsListFragment.kt
> +    override fun reloadFragment() {
je ne comprend pas à quoi ça sert

2023-06-29 19:54 UTC, noeoxycode commented on app/src/main/res/values/strings.xml
>      <string name="hello_first_fragment">Hello first fragment</string>
toutes les valeurs de string ne sont pas dans les deux langues semble-t-il, c'est normal ?

2023-06-29 21:44 UTC, noeoxycode requested changes

2023-06-29 21:44 UTC, noeoxycode commented on app/src/main/java/com/gamefuse/app/myFriendsList/FriendsList.kt
> +        setContentView(R.layout.container)
pas bon le container
j'ai fais comme toi mais c'est moche
on s'appelle je te montre

2023-07-03 10:24 UTC, noeoxycode requested changes

2023-07-03 10:24 UTC, noeoxycode commented on app/src/main/java/com/gamefuse/app/login/LoginFragment.kt
>                      Toast.makeText(context, "Logged in", Toast.LENGTH_SHORT).show()
à supprimer

2023-07-03 10:24 UTC, noeoxycode commented on app/src/main/java/com/gamefuse/app/myFriendsList/FriendsListActivity.kt
> +        nextFragment.arguments = bundle
tu pourrais justifier pourquoi tu as fais comme ça et pas directement passer FriendListFragment() à la ligne 17 au lieu de nextFragment stp ?

2023-07-03 10:24 UTC, noeoxycode commented on app/src/main/java/com/gamefuse/app/myFriendsList/FriendsListActivity.kt
> +        nextFragment.arguments = bundle
notamment avec l'ajout du bundle que je ne comprend pas

2023-07-03 10:24 UTC, noeoxycode commented on app/src/main/java/com/gamefuse/app/myFriendsList/FriendsListFragment.kt
> +        startLoading()
je mettrais plutot le startLoading dans getFriend comme c'est dedans que tu appelles stopLoading

2023-07-03 10:24 UTC, noeoxycode commented on app/src/main/java/com/gamefuse/app/myFriendsList/FriendsListFragment.kt
> +        startLoading()
sois tu fais start et stop dedans sois tout en dehors, mais un mixte n'est pas une bonne idée selon moi

2023-07-03 10:24 UTC, noeoxycode commented on app/src/main/res/layout/fragment_list_friends.xml
> +        android:background="#1976D2"
faut prendre les couleurs du fichier de couleur, en ajouter / supprimer si besoin

2023-07-03 10:24 UTC, noeoxycode commented on app/src/main/res/layout/fragment_list_friends.xml
> +            android:text="Mes amis"
fichier string

2023-07-03 10:24 UTC, noeoxycode commented on app/src/main/res/layout/fragment_list_friends.xml
> +        android:textColor="#000000"
fichier couleur

2023-07-03 10:24 UTC, noeoxycode commented on app/src/main/res/layout/fragment_list_friends.xml
> +        android:background="#1976D2"
fichier couleur

2023-07-03 10:24 UTC, noeoxycode commented on app/src/main/res/layout/fragment_list_friends.xml
> +                android:text="Mes amis"/>
fichier string

2023-07-03 10:24 UTC, noeoxycode commented on app/src/main/res/layout/fragment_list_friends.xml
> +                android:text="Mon profil"/>
fichier string

2023-07-03 10:24 UTC, noeoxycode commented on app/src/main/res/layout/friends_list_component.xml
> +        android:text="Username"
fichier string

2023-07-03 15:11 UTC, ShadowZ11 commented on app/src/main/java/com/gamefuse/app/myFriendsList/FriendsListActivity.kt
> +        nextFragment.arguments = bundle
Alors, pour ce qui est du bundle c'est pas forcément obligatoire mais je trouve que c'est une bonne pratique de le mettre parce que c'est ce qui permet de récupérer des informations entre les activités, le fameux truc du putExtra et getExtra

2023-07-03 18:24 UTC, ShadowZ11 commented on app/src/main/java/com/gamefuse/app/myFriendsList/FriendsListFragment.kt
> +    override fun reloadFragment() {
alors pour ça, j'ai besoin de reload mon fragment après que tu es supprimer un ami par exemple, et depuis l'adapter c'est impossible de récupérer le context (sauf en faisant des trucs pas très clean) donc je passe par une interface qui va ensuite reload mon fragment

2023-07-03 22:35 UTC, noeoxycode approved these changes

2023-07-03 23:33 UTC, merged