Feature/login
GameFuse-PA/mobile pull request #4
Opened 2023-06-29 19:44 UTC by noeoxycode

2023-06-29 19:58 UTC, Pbonnamy requested changes

2023-06-29 19:58 UTC, Pbonnamy commented on app/src/main/java/com/gamefuse/app/API.kt
> +)
a séparer dans des fichiers

2023-06-29 19:58 UTC, Pbonnamy commented on app/src/main/java/com/gamefuse/app/API.kt
> +            .addHeader("NomDeVotreHeader", "ValeurDeVotreHeader")
a enlever je pense

2023-06-29 19:58 UTC, Pbonnamy commented on app/src/main/java/com/gamefuse/app/API.kt
> +        .baseUrl("http://192.168.0.182:3000")
pas sur de ca là

2023-06-29 19:58 UTC, Pbonnamy commented on app/src/main/res/layout/container.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
a quoi ca sert ?

2023-06-29 19:58 UTC, Pbonnamy commented on app/src/main/res/layout/home_page.xml
> +</RelativeLayout>
a quoi ca sert ?

2023-06-29 19:58 UTC, Pbonnamy commented on app/src/main/res/layout/activity_login.xml
> +        android:layout_marginTop="20dp">
je pense pas que tu sois obliger de remttre un lienear layout

2023-06-29 19:58 UTC, Pbonnamy commented on app/src/main/java/com/gamefuse/app/login/LoginFragment.kt
> +                    textViewError.setText("Service unaviable")
a mettre dans une fonction t'as 3 fois les memes lignes

2023-06-29 19:58 UTC, Pbonnamy commented on app/src/main/java/com/gamefuse/app/API.kt
> +
faut faire un truc généric pour ca

2023-06-29 23:04 UTC, noeoxycode commented on app/src/main/java/com/gamefuse/app/API.kt
> +        .baseUrl("http://192.168.0.182:3000")
si, je dois mettre l'ip de ma machine pas localhost, tu as fais ça aussi dans ton projet

2023-07-01 15:28 UTC, Pbonnamy commented on app/src/main/AndroidManifest.xml
> +            android:exported="true"/>
a enlever je pense

2023-07-01 15:30 UTC, Pbonnamy approved these changes

2023-07-01 15:30 UTC, merged