Feature/subscribe
GameFuse-PA/mobile pull request #5
Opened 2023-06-30 16:21 UTC by noeoxycode

2023-07-03 21:58 UTC, Pbonnamy requested changes

2023-07-03 21:58 UTC, Pbonnamy commented on app/src/main/java/com/gamefuse/app/api/model/response/ErrorResponse.kt
> +)
a split dans 2 fichiers

2023-07-03 21:58 UTC, Pbonnamy commented on app/src/main/res/layout/activity_login.xml
> +    tools:context=".login.RegisterActivity">
une erreur je pense

2023-07-03 22:26 UTC, noeoxycode commented on app/src/main/res/layout/activity_login.xml
> +    tools:context=".login.RegisterActivity">
ça je l'ai patch dans forgot password mais je vais le faire ici aussi

2023-07-04 15:10 UTC, Pbonnamy approved these changes

2023-07-04 18:02 UTC, merged