Feature/forgot password
GameFuse-PA/mobile pull request #6
Opened 2023-07-01 10:40 UTC by noeoxycode

2023-07-04 21:16 UTC, Pbonnamy commented on app/src/main/java/com/gamefuse/app/forgotPassword/ForgotPasswordFragment.kt
> +                    Toast.makeText(context, "Mail sent to backup", Toast.LENGTH_SHORT).show()
Message à revoir, "Mail sent to specified address" ou un truc du genre

2023-07-04 22:23 UTC, ShadowZ11 requested changes

2023-07-04 22:23 UTC, ShadowZ11 commented on app/src/main/java/com/gamefuse/app/forgotPassword/ForgotPasswordFragment.kt
> +                    Connect.authToken = response.body().toString()
en vrai c'est pareil que dans le login mais si tu réassignes le authtoken, fait pas un toString sinon c'est imparsable derrière quand on va l'appeler à cause du fait qu'il va te renvoyer la classe en chaine de caractère, remplace plutot en faisant ça: Connect.authToken = Gson().toJson(response.body())

2023-07-04 22:27 UTC, ShadowZ11 commented on app/src/main/java/com/gamefuse/app/forgotPassword/ForgotPasswordFragment.kt
> +        }
en vrai c'est bien mais faut faire attention en démarrant des activité parce que ça peut vite devenir des genre de boucles infini si tu finish pas, là le user peut appuyer sur le bouton "forgot password" puis revenir au login puis revenir au forgot etc... et la mémoire au bout d'un moment elle va prendre cher

2023-07-05 21:04 UTC, noeoxycode commented on app/src/main/java/com/gamefuse/app/forgotPassword/ForgotPasswordFragment.kt
> +        }
donc close l'activité ou faire un singleton ?

2023-07-05 21:04 UTC, noeoxycode commented on app/src/main/java/com/gamefuse/app/forgotPassword/ForgotPasswordFragment.kt
> +                    Connect.authToken = response.body().toString()
ah oui mb je vais corriger

2023-07-05 21:16 UTC, noeoxycode commented on app/src/main/java/com/gamefuse/app/forgotPassword/ForgotPasswordFragment.kt
> +                    Connect.authToken = response.body().toString()
en fait je vais juste le retirer on ne s'en sert pas dans forgot password

2023-07-05 21:47 UTC, ShadowZ11 requested changes

2023-07-05 21:47 UTC, ShadowZ11 commented on app/src/main/res/values-fr/strings.xml
> +    <string name="mail_sent_if_exist">Mail envoyé à l adresse spécifiée</string>
je pense que le texte aurait été mieux du style "Si votre adresse email est valide vous recevrez un email pour changer votre mot de passe", parce que la tu confirmes que l'email est envoyé même si le mail est pas valide

2023-07-05 22:27 UTC, ShadowZ11 approved these changes

2023-07-16 15:33 UTC, merged