Feature/search friend
GameFuse-PA/mobile pull request #7
Opened 2023-07-04 21:14 UTC by ShadowZ11

Ajout de la page rechercher un ami avec la possibilité avec call api

2023-07-07 19:42 UTC, Pbonnamy requested changes

2023-07-07 19:42 UTC, Pbonnamy commented on app/src/main/java/com/gamefuse/app/searchFriend/SearchFriendFragment.kt
> +                                "https://www.pngitem.com/pimgs/m/146-1468479_my-profile-icon-blank-profile-picture-circle-hd.png"
a mettre dans les fichiers de l'app

2023-07-07 19:42 UTC, Pbonnamy commented on app/src/main/java/com/gamefuse/app/searchFriend/SearchFriendFragment.kt
> +                    e.message?.let { Log.e("Erreur requête", it) }
a enlever je pense

2023-07-07 19:42 UTC, Pbonnamy commented on app/src/main/java/com/gamefuse/app/searchFriend/SearchFriendFragment.kt
> +    fun Int.dpToPx(): Int = (this * Resources.getSystem().displayMetrics.density).toInt()
c pour quoi ca ?

2023-07-07 19:42 UTC, Pbonnamy commented on app/src/main/java/com/gamefuse/app/searchFriend/adapter/SearchFriendAdapter.kt
> +                e.printStackTrace()
a remplacer par un message d'erreur

2023-07-10 07:51 UTC, ShadowZ11 commented on app/src/main/java/com/gamefuse/app/searchFriend/SearchFriendFragment.kt
> +    fun Int.dpToPx(): Int = (this * Resources.getSystem().displayMetrics.density).toInt()
C'est une fonction qui permet de transformer les dp en px, pour la ligne qui se trouve en dessous dans la recycler view quand tu mets des decorateur

2023-07-10 07:57 UTC, ShadowZ11 commented on app/src/main/java/com/gamefuse/app/searchFriend/SearchFriendFragment.kt
> +                    e.message?.let { Log.e("Erreur requête", it) }
Je préférais le garder ça faisait du logging de debuggage

2023-07-10 08:21 UTC, Pbonnamy approved these changes

2023-07-10 08:24 UTC, merged